// BRIGHT Website
// French translations

const fr_translations = {
    "nav-research": "Recherches",
    "nav-publications": "Publications",
    "nav-team": "Equipe",
    "nav-join": "Nous rejoindre",
    "nav-contact": "Contact",

    "research-title": "AXES DE RECHERCHE",
    "research-summary": "Le laboratoire se concentre sur l'étude des bases génétiques et neuronales des troubles psychiatriques, avec une attention particulière portée à l'utilisation des données génétiques et de neuroimagerie pour identifier les mécanismes biologiques qui les sous-tendent. Nous travaillons également sur le développement de nouvelles méthodes d'analyse pour ces données, et sur leur application à la recherche sur les troubles psychiatriques.",

    "fmri-title": "Vers une nouvelle classification dimensionnelle des conditions neurodéveloppementales et psychiatriques grâce aux méthodes de neuroimagerie et de génétique",
    "fmri-content": "La recherche en psychiatrie s’est longtemps fondée sur une approche descendante (top-down), consistant à comparer des groupes de patient·es à des témoins afin d’identifier des biomarqueurs. Cette stratégie a conduit à des résultats souvent incohérents et difficilement reproductibles, reflétant une réalité clinique marquée par une forte hétérogénéité au sein même des catégories diagnostiques. En effet, les profils cliniques sont très variés, et les comorbidités (tel qu’un diagnostic de TDAH qui accompagnerait un diagnostic de TSA) constituent la norme plutôt que l’exception. Cette diversité pourrait s’expliquer, en partie, par des mécanismes génétiques complexes tels que la pléiotropie (des gènes impliqués dans plusieurs troubles) et la polygénicité (de nombreux gènes associés à un même trouble). Ces constats appellent à repenser la classification des troubles neurodéveloppementaux et psychiatriques, en s’appuyant davantage sur des dimensions biologiques objectives que sur la seule symptomatologie clinique.<br><br>Notre laboratoire utilse une approche ascendante (bottom-up), qui consiste à partir de variants génétiques associées aux conditions psychiatriques pour étudier leur impact sur des endophénotypes cérébraux, avec pour objectif de les lier à des dimensions cliniques (et non des catégories diagnostiques binaires). Cette stratégie nous a déjà permis d’identifier des profils fonctionnels cérébraux partagés entre plusieurs diagnostics psychiatriques - tel que la surconnectivité thalamo-sensorimotrice présente dans l’autisme mais aussi dans la schizophrénie et les TOC. Nous poursuivons actuellement cette approche en explorant entre autres l’impact des variants génétiques sur le développement cérébral précoce (chez le nourisson), ou encore l’effet de scores de charge polygénique sur l’imagerie multimodale et l’EEG chez l’enfant.<br><br>En parallèle, nous adoptons une perspective transdiagnostique top-down à large échelle au sein du consortium ENIGMA, notamment à travers des projets de neuroimagerie fonctionnelle, pour mieux comprendre les dimensions cérébrales communes à plusieurs conditions.",

    "methods-title": "Harmoniser les méthodes d’analyse en neuroimagerie fonctionnelle",
    "methods-content": "La neuroimagerie fonctionnelle en psychiatrie a fait face à un défi majeur cette dernière décennie, à savoir une faible reproductibilité des résultats. Cette instabilité s’explique principalement par deux facteurs: l’hétérogénéité des diagnostics psychiatriques, qui regroupent des patient·es aux profils très variés, la diversité des méthodes d’analyse utilisées d’un groupe de recherche à l’autre, influençant considérablement les résultats.<br><br>Notre laboratoire co-dirige le groupe de travail ENIGMA-rsfMRI, qui vise à harmoniser les protocoles d’analyse des données d’IRM fonctionnelle au repos. Nous développons des approches multiverses, qui consistent à tester systématiquement l’effet des différents choix méthodologiques (notamment les stratégies de débruitage) sur les résultats obtenus. Ce travail est essentiel pour garantir la robustesse et la comparabilité des études et des diagnostics psychiatriques et neurologiques à grande échelle, condition indispensable pour faire progresser la neuroimagerie vers des applications cliniques fiables.",

    "anorexia-title": "Trajectoires cérébrales et pronostic de l’anorexie mentale",
    "anorexia-content": "L’anorexie mentale est associée à l’un des taux de mortalité les plus élevés parmi toutes les maladies psychiatriques. Ce taux de mortalité résulte d’une combinaison de complications médicales associées à leur trouble alimentaire et de décès par suicide, augmentant d’environ 5 % à chaque décennie de maladie. L’anorexie débute généralement à l’adolescence et se caractérise par une restriction persistante et sévère de l’alimentation, un poids faible et une perturbation de l’image corporelle. Les rechutes sont fréquentes après la restauration pondérale, avec seulement ~60% des patients atteignant une rémission durable. Malgré la gravité de cette pathologie, les mécanismes neurobiologiques impliqués dans le risque de rechute et la réponse aux traitements demeurent largement méconnus.<br><br>Pour y répondre, nous menons une étude longitudinale à l’hôpital CHU Sainte-Justine, suivant une cohorte de patient·es âgé·es de 9 à 16 ans à différents stades de leur parcours clinique et après leur sortie de l’hôpital. À chaque étape, nous recueillons des données d’imagerie cérébrale multimodale ainsi que des évaluations cliniques et cognitives.<br><br>Notre objectif est de développer des outils de prédiction du risque de rechute en analysant l’état de récupération cérébrale post-renutrition, combiné à d’autres marqueurs cliniques. L’identification de marqueurs précoces de rechute permettra d’individualiser les prises en charge et de prévenir l’évolution vers des formes chroniques. Ce projet s’inscrit dans une dynamique de recherche internationale, que notre laboratoire co-pilote au sein du groupe de travail Eating Disorders du consortium ENIGMA, réunissant plus de 20 laboratoires à travers le monde.Au-delà de ses implications cliniques, ce projet offre une opportunité unique d’explorer la plasticité cérébrale et les mécanismes d’adaptation du cerveau en contexte de dénutrition prolongée.",

    "publications-title": "PUBLICATIONS",

    "team-title": "L'EQUIPE",

    "funding-title": "FINANCEMENT",

    "recruitment-title": "NOUS REJOINDRE",
    "recruitment-summary": "Nous sommes toujours à la recherche de personnes talentueuses et motivées pour rejoindre notre équipe. Si vous êtes intéressé(e), veuillez envoyer votre CV et une lettre de motivation à <a href='mailto:clara.moreau@umontreal.ca'>clara.moreau@umontreal.ca</a>. Nous sommes particulièrement intéressés par des candidat(e)s ayant une formation en neurosciences, psychologie, informatique ou dans des domaines connexes. Nous offrons un environnement de recherche dynamique et collaboratif, avec des opportunités de développement professionnel et de formation.",

    "contact-title": "CONTACT",
}
